spring.application.name=rocmovies
server.port=9090
spring.webflux.base-path=/rocmovies
server.error.include-binding-errors=always
server.error.include-message=always
spring.thymeleaf.suffix =.html
spring.jpa.hibernate.ddl-auto=create
spring.r2dbc.url=r2dbc:mysql://127.0.0.1:3306/rocmovies
spring.r2dbc.username=root
spring.r2dbc.password=pwroot
spring.profiles.active=dev
spring.sql.init.mode=always
